### PR TITLE
usability updates

### PR DESCRIPTION
**Pull request by Gateworks**

### CODE REVIEW

**Comment by sasamy** [comment]
Hi Tim, I understood what was my error - in my case the standard is always defined because of noises even if the camera isn't connected therefore I have no problems. If just to turn off autodetection and to set NTSC by default - then it will be impossible to capture PAL signal (at least in gstreamer-imx). I think that it is necessary to rewrite tw6869_querystd and add programming of registers of the video decoder according to the current video standard (NTSC by default) to tw6869_vch_dma_cfg.

**Comment by Gateworks** [comment]
Alexander,

I haven't tested PAL yet, but I did notice that the s_fmt ioctl isn't updating the tw6869 registers properly and so I wouldn't expect it to work without that fixed.

By the way, do you know what upstream solution exists to allow zero-copy buffers to be used between v4l2src and IMX IPU/VPU/GPU (ie coda)? I'm thinking that some of the new v2b stuff has provisions for this and/or the coda driver handles the dma more properly than the fsl kernel?

Tim

**Comment by sasamy** [comment]
Tim,
it is correct - s_fmt ioctl doesn't update registers - only checks a correctness of programmable parameters and saves the copy. Registers are programmed just before switching ON DMA:
https://github.com/sasamy/tw6869/blob/master/tw6869-video.c#L398
https://github.com/sasamy/tw6869/blob/master/tw6869-video.c#L274

This approach makes it easy to restore the state of the channels even after the power is turned off (suspend to disk):
https://github.com/sasamy/tw6869/blob/master/tw6869-core.c#L340

IPU/GPU drivers In mainline Linux are still in the WIP and at least for a tv6869 they are still unsuitable.

**Comment by sasamy** [comment]
Maybe I misunderstood the question - of course the Linux kernel has a standard mechanism for export / import of DMA buffers (zero-copy)

https://www.kernel.org/doc/Documentation/dma-buf-sharing.txt
https://linuxtv.org/downloads/v4l-dvb-apis/dmabuf.html

for drivers who use vb2 API is available "out of the box"
https://github.com/sasamy/tw6869/blob/master/tw6869-video.c#L923
https://github.com/sasamy/tw6869/blob/master/tw6869-video.c#L927

**Pull request merged**
